{
 "title": "NLSRig",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rig",
    "label": "Rig",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(bucket: \"miner\", tag: \"friendlyName\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Miner Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> group(columns: [\"friendlyName\"])\n  |> last()\n  |> yield(name: \"_value\")"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Ping" } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ping\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> group(columns: [\"friendlyName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Last Boot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"start_time\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"rig03\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns:[\"friendlyName\"])\n  |> map(fn: (r) => ({ r with _value: r._value * 1000000000 }))\n  |> toTime()"
    }
   ]
  },
  {
   "title": "Total hashrate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_hashrate_raw\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> group(columns: [\"_measurement\",\"friendlyName\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"hashrate\")"
    }
   ]
  },
  {
   "title": "Hashrate x Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hashrate_raw\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature x Device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_power_consumption\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> group(columns: [\"_measurement\",\"friendlyName\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"Power\")"
    }
   ]
  },
  {
   "title": "Power Consumption x Device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"power\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fan Speed % x Device",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total hashrate 24H AVG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_hashrate_raw\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"rig03\")\n  |> group(columns: [\"_measurement\",\"friendlyName\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> timedMovingAverage(every: 15m, period: 1d)\n  |> yield(name: \"hashrate\")"
    }
   ]
  },
  {
   "title": "Accepted Shares x Device",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_accepted_shares\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> derivative(unit: 1m, nonNegative: true)\n  |> map(fn: (r) => ({\n      r with\n      _field: \"Device ${r.id} (${r.friendlyName})\"\n    })\n  )\n  |> yield(name: \"derivative\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_accepted_shares\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"rig03\")\n  |> derivative(unit: 1m, nonNegative: true)\n  |> group(columns: [\"_field\",\"friendlyName\"], mode: \"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 5)\n  |> map(fn: (r) => ({\n      r with\n      _field: \"Moving Average (${r.friendlyName})\"\n    })\n  )\n  |> yield(name: \"average\")"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"miner\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"miner-device-status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")\n  |> filter(fn: (r) => r[\"friendlyName\"] == \"${rig}\")\n  |> group(columns: [\"friendlyName\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}